### PR TITLE
Release 3.1.10 - Password reset and security requirements, bug fixes

### PR DESCRIPTION
**Pull request by mitianisb**

### CODE REVIEW

**Review by wlongabaugh — CHANGES_REQUESTED** [review]
The what's new section is hardwired now to 3.1.9. It needs to go back to [[RELEASE_VERSION]], I believe?

**Review by wlongabaugh — CHANGES_REQUESTED** [review]
[innerHTML] has been dropped from sample-edit.component.html. All text should be shown in [innerHTML] to make sure that any markup is displayed correctly. You should still be able to fix the address spacing without taking it out of innerHTML?

**Review by wlongabaugh — COMMENTED** [review]
In UserServiceImpl, there is a new wildcard import java.util.*. This is not a showstopper, but I prefer explicit imports to know exactly what is needed.

**Review by wlongabaugh — CHANGES_REQUESTED** [review]
Do files like software/cananolab-webapp/web/cananolab-client-main-display-change-password-change-password-module.js, software/cananolab-webapp/web/cananolab-client-main-display-change-password-change-password-module.js.map, and software/cananolab-webapp/web/default\~cananolab-client-main-display-samples-characterization-editcharacterization-editcharacteriza~6b4b351c.js really belong in the repo? Aren't these outputs from the Angular compiler?

**Review by wlongabaugh — COMMENTED** [review]
In the compiled file `software/cananolab-webapp/web/index.html` it looks like  `<base href="/">` changed to `<base href=".">`. What is that about? And is this going to be a problem?  @s-paquette ?

**Review by s-paquette — CHANGES_REQUESTED** [review]
Just a quick note, there were several instances of the --base-href being set to "." instead of / for the ng build command. This is incorrect, and I've fixed it in master and test. If you do a pull from test you should be able to pick up this fix. You'll want to rebuild and re-commit the built angular files so the repo is up to date.

**Comment by mitianisb** [comment]
@s-paquette I did pull test and master before making this PR. How do I "rebuild and re-commit the built angular files"? Is it by running the "ng build" command copy all the /web content like we used to do?

**Comment by mitianisb** [comment]
@wlongabaugh @s-paquette I made changes to address all the previous comments and they are in this PR now too. Please let me know if there is any other change needed. Thanks for reviewing!

**Comment by mitianisb** [comment]
I am not sure how to mark the requested changes addressed to unblock the PR? Maybe need you to remove the blockers?

**Comment by mitianisb** [comment]
I cannot find a way to resolve the conversation, I think it may be because the comments are not made inline in the code. Since Bill is on vacation, I will close this PR and make a new one so we can release as planned tomorrow.

**Pull request closed without merging**
